[PAGOPA-1564] feat: added update_cup_iban.py script to update cup iban in ecConfigTable
pagopa/pagopa-canone-unico pull request #47
Opened 2024-03-20 16:58 UTC by aferracci

#### List of Changes

- Added `update_cup_iban.py` script to update the iban codes in `ecConfigTable` with the last choice of the CI (CUP label)

#### Motivation and Context

Update the CUP iban in the config table

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-03-22 10:18 UTC, pasqualespica requested changes
LGTM 👍

2024-03-22 10:18 UTC, pasqualespica commented on scripts/update_cup_iban.py
> +            api_url = f"{self.apim_url}/creditorinstitutions/{id_ci}/ibans/enhanced?label=0201138TS"
add comment before this line with somethig like that
```
2 PROVINCIA / CITTA' METROPOLITANA	1	SERVIZI PROVINCIALI / CITTA' METROPOLITANA	
Tributi e diritti gestiti direttamente dall'Ente Provinciale.	
138	Canone Unico Patrimoniale - CORPORATE	
TS	(SOLUZIONE CENTRALE GESTITA DA PAGOPA) 
La Legge di Bilancio 2020 (Legge n. 160/2019) ha previsto, a decorrere dal 1° gennaio 2021, l’istituzione  di un “canone unico patrimoniale” 
che unifica in un solo prelievo TOSAP, COSAP, l’imposta comunale sulla PUBBLICITÀ e AFFISIONI, ed altre imposte locali.
Questa soluzione è gestita centralmente da Pagopa S.p.a.	
36	9/0201138TS/	05/03/2021	01/01/2080	Attività produttive e commercio + Altro	
```
to give label `0201138TS` context

2024-03-22 10:18 UTC, pasqualespica commented on scripts/update_cup_iban.py
> +                for i, entity in enumerate(entities):
this script should be run after init of `pagopapcanoneunicosaecconfigtable` ?
what is the first step before `python3 update_cup_iban.py  ...` 

i.e. this script will update the ibans but which one initially creates the entities?

2024-03-22 10:59 UTC, aferracci commented on scripts/update_cup_iban.py
> +                for i, entity in enumerate(entities):
The first script to launch is `buildEcConfigTable.py` but we must take into account that it requires to be reviewed as it is currently based on data downloaded from PdA that has been dismissed, and at the moment we don't have the complementary service exposed by SelfCare/Area Riservata.
Anyway I'm going to better explicit this situation in readme file

2024-03-25 10:19 UTC, pasqualespica approved these changes
👍

2024-03-25 10:19 UTC, merged